environment:

  global:
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - git submodule update --init
  - cd machinelearning
  - git submodule update --init --recursive
  - cd ..
  - set DOTNET_CLI_TELEMETRY_OPTOUT=1

build: off

before_build:
  - cmd: dotnet --version

before_test:
  - cd machinelearning
  - cmd /C build.cmd
  - cmd /C build.cmd -Release
  - cd ..
  # copy release
  - mkdir machinelearning\dist\Release
  - copy machinelearning\packages\lightgbm\2.2.1.1\runtimes\win-x64\native machinelearning\bin\x64.Release\Native
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.Api\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.Ensemble\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.FastTree\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.HalLearners\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.ImageAnalytics\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.KMeansClustering\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.Maml\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.LightGBM\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.Onnx\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.OnnxTransform\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.PCA\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.PipelineInference\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.StandardLearners\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.TensorFlow\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\bin\AnyCPU.Release\Microsoft.ML.TimeSeries\netstandard2.0\*.dll machinelearning\dist\Release
  - copy machinelearning\packages\lightgbm\2.2.1.1\runtimes\win-x64\native machinelearning\bin\x64.Release\Native
  - copy machinelearning\packages\mlnetmkldeps\0.0.0.7\runtimes\win-x64\native machinelearning\bin\x64.Release\Native
  - copy machinelearning\packages\google.protobuf\3.5.1\lib\netstandard1.0 machinelearning\bin\x64.Release\Native
  - copy machinelearning\bin\x64.Release\Native\*.dll machinelearning\dist\Release
  # copy debug
  - mkdir machinelearning\dist\Debug
  - copy machinelearning\packages\lightgbm\2.2.1.1\runtimes\win-x64\native machinelearning\bin\x64.Debug\Native
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.Api\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.Ensemble\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.FastTree\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.HalLearners\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.ImageAnalytics\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.KMeansClustering\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.Maml\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.LightGBM\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.Onnx\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.OnnxTransform\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.PCA\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.PipelineInference\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.StandardLearners\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.TensorFlow\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\bin\AnyCPU.Debug\Microsoft.ML.TimeSeries\netstandard2.0\*.dll machinelearning\dist\Debug
  - copy machinelearning\packages\lightgbm\2.2.1.1\runtimes\win-x64\native machinelearning\bin\x64.Debug\Native
  - copy machinelearning\packages\mlnetmkldeps\0.0.0.7\runtimes\win-x64\native machinelearning\bin\x64.Debug\Native
  - copy machinelearning\packages\google.protobuf\3.5.1\lib\netstandard1.0 machinelearning\bin\x64.Debug\Native
  - copy machinelearning\bin\x64.Debug\Native\*.dll machinelearning\dist\Debug
  # build machinelearningext
  - cd machinelearningext
  - cmd /C dotnet build -c Debug
  - cmd /C dotnet build -c Release
  - cd ..
  # final copy
  - copy machinelearning\bin\x64.Release\Native\*.dll machinelearningext\bin\AnyCPU.Release\TestProfileBenchmark\netcoreapp2.1
  - copy machinelearning\bin\x64.Debug\Native\*.dll machinelearningext\bin\AnyCPU.Debug\TestProfileBenchmark\netcoreapp2.1
  - copy machinelearning\bin\x64.Release\Native\*.dll machinelearningext\bin\AnyCPU.Release\TestMachineLearningExt\netcoreapp2.1
  - copy machinelearning\bin\x64.Debug\Native\*.dll machinelearningext\bin\AnyCPU.Debug\TestMachineLearningExt\netcoreapp2.1
  - copy machinelearning\bin\x64.Release\Native\*.dll machinelearningext\bin\AnyCPU.Release\DocHelperMlExt\netstandard2.0
  - copy machinelearning\bin\x64.Debug\Native\*.dll machinelearningext\bin\AnyCPU.Debug\DocHelperMlExt\netstandard2.0

test_script:
  # unit tests for machinelearning (too long)
  # - cd machinelearning
  # - cmd /C build.cmd -runTests -Release
  # - cd ..
  # unit tests for machinelearningext
  - cd machinelearningext
  - cmd /C dotnet test -c Debug TestMachineLearningExt -v n
  - cmd /C dotnet test -c Release TestMachineLearningExt -v n
  - cd ..

after_test:
  - if not exist dist mkdir dist
  - if not exist dist\Release mkdir dist\Release
  - if not exist dist\Debug mkdir dist\Debug
  - python -u copy_binaries.py Release dist\Release
  - python -u copy_binaries.py Debug dist\Debug
  # benchmark
  - copy _tests\1.0.0.0\Release\TestScikitAPITrain\*.txt dist

artifacts:
  - path: dist
    name: machinelearningext
