resources:
  containers:
  - container: LinuxContainer
    image: microsoft/dotnet-buildtools-prereqs:centos-7-b46d863-20180719033416

phases:
- template: /machinelearning/machinelearning/build/ci/phase-template.yml
  parameters:
    name: Linux
    buildScript: ./machinelearning/machinelearning/build.sh
    queue:
      name: Hosted Ubuntu 1604
      container: LinuxContainer

- template: /machinelearning/build/ci/phase-template.yml
  parameters:
    name: Windows_x64
    buildScript: build.cmd
    queue:
      name: Hosted VS2017

- template: /machinelearning/build/ci/phase-template.yml
  parameters:
    name: MacOS
    buildScript: ./machinelearning/build.sh
    queue:
      name: Hosted macOS
